### ISSUE TITLE
Are PublicKeyCredentialCreationOptions and PublicKeyCredentialRequestOptions meant to be serialized to JSON with ObjectConverter?

### ISSUE THREAD

**Issue by epheat** [webauthn4j/webauthn4j#316]
**Is your feature request related to a problem? Please describe.**
I'm trying to take the PublicKeyCredentialCreationOptions & PublicKeyCredentialRequestOptions classed provided by this library, and serialize them to JSON. The PublicKeyCredentialCreationOptions already has many Jackson annotations describing the property names, and quite a few serializers/deserializers registered in the ObjectConverter class, so I figured this would be possible. It seems to work (mostly) when I do the following:
```
new ObjectConverter().getJsonConverter().writeValueAsString(creationOptions);
```
However, one issue I'm facing is that the serialization of `user.id` and `excludeCredentials[].id` use the default Base64 encoding instead of Base64Url encoding used everywhere in the spec. The challenge, on the other hand, is serialized with Base64Url, as there is a ChallengeSerializer registered which explicitly uses Base64Url encoding. Is JSON serialization/deserialization within the scope of this library?

Thanks

**Comment by ynojima** [comment]
Thank you for submitting issue. As far as I know, there is no definition for encoding format of `user.id` and `excludeCredentials[].id` . If there is, I appreciate if you let me know. That's why I leave it for default Base64 encoding.
Maybe I will add some mechanism to choose encoding, for now, there is no built-in way to realize it in WebAuthn4J.

But if you prefer Base64Url encoding, you can specify encoding by Jackson mixin mechanism.
https://dzone.com/articles/jackson-mixin-to-the-rescue

Here is a sample mixin for `PublicKeyCredentialDescriptor`.
https://github.com/webauthn4j/webauthn4j-spring-security/blob/redesignWebAuthnProcessingFilter/webauthn4j-spring-security-core/src/main/java/com/webauthn4j/springframework/security/endpoint/PublicKeyCredentialDescriptorMixin.java

Define your own mixin in your application code and register it to `ObjectMapper` instance wrapped in `ObjectConverter`.
you can inject your own `ObjectMapper` into `ObjectConverter` through its constructor.

**Comment by epheat** [comment]
Thanks for your help and pointing me towards examples, I'll try adding my own mixin to have finer grain control over the encoding.
