### ISSUE TITLE
 CoreCredentialRecord incompatible with Lombok

### ISSUE THREAD

**Issue by Vloeck** [webauthn4j/webauthn4j#976]
**Describe the bug**
 CoreCredentialRecord incompatible with Lombok

All the methods in the interface `CoreCredentialsRecord` have different Parameters
e.g.
```
@Nullable Boolean isUvInitialized() ;
void setUvInitialized(boolean value);
```
This makes it incompatible with Lombok, because you cannot generate either Setters or Getters.
There is no reason to make the setters only accept primitive values since the getter is explicitely annotated to be Nullable.

**Additional context**
also the "is" prefix should only be used for booleans, not for Boolean, see https://stackoverflow.com/a/69414543

**Comment by ynojima** [comment]
This is an intentional design.
For backward-compatibility with an existing credential without UV initialized value, `isUvInitialized()` is nullabe.
But since webauthn4j won't update UV initialized value with `null`, `setUvInitialized` takes primitive boolean.

You should write your getter and setter manually without using lombok when implementing `CoreCredentialRecord`.
